/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico.administrador;

import java.awt.Image;
import javax.swing.ImageIcon;
import modelo.Empresa;


public class Administrador extends javax.swing.JFrame {
    
    private Empresa e;

    /**
     * Creates new form VentanaAdmin
     */
    
    public Administrador(Empresa e) {
        initComponents();
        this.e=e;
        this.setTitle("Administrador");
        this.setLocation(700,300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alta = new javax.swing.JButton();
        bajaVehiculo = new javax.swing.JButton();
        consulta = new javax.swing.JButton();
        ventas = new javax.swing.JButton();
        bajaCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        alta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alta.setText("Alta vehiculo");
        alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaActionPerformed(evt);
            }
        });

        bajaVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bajaVehiculo.setText("Baja vehiculo");
        bajaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaVehiculoActionPerformed(evt);
            }
        });

        consulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consulta.setText("Consulta vehiculos");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        ventas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ventas.setText("Consulta ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        bajaCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bajaCliente.setText("Baja cliente");
        bajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaClienteActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bajaCliente)
                    .addComponent(alta)
                    .addComponent(ventas)
                    .addComponent(bajaVehiculo)
                    .addComponent(consulta)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(alta)
                .addGap(18, 18, 18)
                .addComponent(bajaVehiculo)
                .addGap(18, 18, 18)
                .addComponent(consulta)
                .addGap(18, 18, 18)
                .addComponent(ventas)
                .addGap(18, 18, 18)
                .addComponent(bajaCliente)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaActionPerformed
        AltaVehiculo rg = new AltaVehiculo(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_altaActionPerformed

    private void bajaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaVehiculoActionPerformed
        BajaVehiculo rg = new BajaVehiculo(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_bajaVehiculoActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        Consulta rg = new Consulta(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_consultaActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        VentanaVenta rg = new VentanaVenta(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_ventasActionPerformed

    private void bajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaClienteActionPerformed
        BajaCliente rg = new BajaCliente(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_bajaClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alta;
    private javax.swing.JButton bajaCliente;
    private javax.swing.JButton bajaVehiculo;
    private javax.swing.JButton consulta;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
