package grafico.administrador;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Fichero;
import modelo.Motocicleta;
import modelo.Todoterreno;
import modelo.Turismo;
import modelo.Vehículo;

public class AltaVehículo extends javax.swing.JFrame {

    private JFrame principal;
    private String tipo = "";

    /** Creates new form Altas */
    public AltaVehículo(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        muestraMotocicleta();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Alta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        Matrícula = new javax.swing.JTextField();
        Modelo = new javax.swing.JTextField();
        Potencia = new javax.swing.JSpinner();
        Color = new javax.swing.JTextField();
        Matriculación = new javax.swing.JFormattedTextField();
        Kilómetros = new javax.swing.JSpinner();
        Precio = new javax.swing.JSpinner();
        TipoVehículo = new javax.swing.JComboBox<>();
        Automóvil = new javax.swing.JLayeredPane();
        EtiquetaAutomóvilCambio = new javax.swing.JLabel();
        Cambio = new javax.swing.JComboBox<>();
        EtiquetaAutomóvilCombustible = new javax.swing.JLabel();
        Plazas = new javax.swing.JSpinner();
        Combustible = new javax.swing.JComboBox<>();
        EtiquetaAutomóvilPlazas = new javax.swing.JLabel();
        Todoterreno = new javax.swing.JLayeredPane();
        EtiquetaTodoterrenoTracción = new javax.swing.JLabel();
        Tracción = new javax.swing.JComboBox<>();
        Turismo = new javax.swing.JLayeredPane();
        Puertas = new javax.swing.JSpinner();
        EtiquetaTurismoPuertas = new javax.swing.JLabel();
        Motocicleta = new javax.swing.JLayeredPane();
        EtiquetaMotocicletaCilindrada = new javax.swing.JLabel();
        Tipo = new javax.swing.JComboBox<>();
        EtiquetaMotocicletaTipo = new javax.swing.JLabel();
        Cilindrada = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Alta");

        Alta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Alta.setText("Alta");
        Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/OcasionCar_Logo.png"))); // NOI18N

        jLabel3.setText("Matrícula");

        jLabel4.setText("Marca");

        jLabel5.setText("Modelo");

        jLabel6.setText("Potencia");

        jLabel7.setText("Color");

        jLabel8.setText("Matriculación");

        jLabel9.setText("Kilómetros");

        jLabel10.setText("Precio");

        Matrícula.setToolTipText("");

        Matriculación.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        Matriculación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaciónActionPerformed(evt);
            }
        });

        TipoVehículo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motocicleta", "Todoterreno", "Turismo" }));
        TipoVehículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoVehículoActionPerformed(evt);
            }
        });

        EtiquetaAutomóvilCambio.setText("Cambio");

        Cambio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automático" }));

        EtiquetaAutomóvilCombustible.setText("Combustible");

        Combustible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Diésel", "Híbrido", "Eléctrico" }));
        Combustible.setToolTipText("");

        EtiquetaAutomóvilPlazas.setText("Plazas");

        Automóvil.setLayer(EtiquetaAutomóvilCambio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Automóvil.setLayer(Cambio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Automóvil.setLayer(EtiquetaAutomóvilCombustible, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Automóvil.setLayer(Plazas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Automóvil.setLayer(Combustible, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Automóvil.setLayer(EtiquetaAutomóvilPlazas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AutomóvilLayout = new javax.swing.GroupLayout(Automóvil);
        Automóvil.setLayout(AutomóvilLayout);
        AutomóvilLayout.setHorizontalGroup(
            AutomóvilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutomóvilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AutomóvilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutomóvilLayout.createSequentialGroup()
                        .addComponent(EtiquetaAutomóvilCombustible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Combustible, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutomóvilLayout.createSequentialGroup()
                        .addGroup(AutomóvilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EtiquetaAutomóvilPlazas)
                            .addComponent(EtiquetaAutomóvilCambio))
                        .addGap(48, 48, 48)
                        .addGroup(AutomóvilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cambio, 0, 1, Short.MAX_VALUE)
                            .addComponent(Plazas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        AutomóvilLayout.setVerticalGroup(
            AutomóvilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutomóvilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AutomóvilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaAutomóvilCombustible)
                    .addComponent(Combustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AutomóvilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaAutomóvilCambio)
                    .addComponent(Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(AutomóvilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaAutomóvilPlazas)
                    .addComponent(Plazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        EtiquetaTodoterrenoTracción.setText("Tracción");

        Tracción.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4x2", "4x4" }));

        Todoterreno.setLayer(EtiquetaTodoterrenoTracción, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Todoterreno.setLayer(Tracción, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TodoterrenoLayout = new javax.swing.GroupLayout(Todoterreno);
        Todoterreno.setLayout(TodoterrenoLayout);
        TodoterrenoLayout.setHorizontalGroup(
            TodoterrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TodoterrenoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaTodoterrenoTracción)
                .addGap(18, 18, 18)
                .addComponent(Tracción, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TodoterrenoLayout.setVerticalGroup(
            TodoterrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TodoterrenoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TodoterrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaTodoterrenoTracción)
                    .addComponent(Tracción, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        EtiquetaTurismoPuertas.setText("Puertas");

        Turismo.setLayer(Puertas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Turismo.setLayer(EtiquetaTurismoPuertas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TurismoLayout = new javax.swing.GroupLayout(Turismo);
        Turismo.setLayout(TurismoLayout);
        TurismoLayout.setHorizontalGroup(
            TurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TurismoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaTurismoPuertas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Puertas)
                .addContainerGap())
        );
        TurismoLayout.setVerticalGroup(
            TurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TurismoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaTurismoPuertas)
                    .addComponent(Puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        EtiquetaMotocicletaCilindrada.setText("Cilindrada");

        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciclomotor", "Sport", "Scooter", "Custom", "Cross", "Trail" }));
        Tipo.setToolTipText("");

        EtiquetaMotocicletaTipo.setText("Tipo");

        Cilindrada.setToolTipText("");

        Motocicleta.setLayer(EtiquetaMotocicletaCilindrada, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Motocicleta.setLayer(Tipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Motocicleta.setLayer(EtiquetaMotocicletaTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Motocicleta.setLayer(Cilindrada, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MotocicletaLayout = new javax.swing.GroupLayout(Motocicleta);
        Motocicleta.setLayout(MotocicletaLayout);
        MotocicletaLayout.setHorizontalGroup(
            MotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MotocicletaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtiquetaMotocicletaCilindrada)
                    .addComponent(EtiquetaMotocicletaTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        MotocicletaLayout.setVerticalGroup(
            MotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MotocicletaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaMotocicletaTipo)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MotocicletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaMotocicletaCilindrada)
                    .addComponent(Cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Kilómetros, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Matriculación, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Todoterreno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Turismo)
                                    .addComponent(Motocicleta, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Matrícula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(Automóvil))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TipoVehículo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoVehículo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Matrícula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Automóvil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Matriculación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Kilómetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Motocicleta)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Todoterreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Alta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Turismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(435, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//alta    
private void AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaActionPerformed
// TODO add your handling code here:
    try {
        //############# Vehículo ###############
         String tipoVehículo=TipoVehículo.getSelectedItem().toString(),
                 matrícula=Matrícula.getText().toString(),marca=Marca.getText().toString(),
                 modelo=Modelo.getText().toString(),color=Color.getText().toString(),
                 matriculación=Matriculación.getText().toString();
         int potencia=(Integer)Potencia.getValue(),
                 kilometros=(Integer)Kilómetros.getValue();
         double precio=(Double)Precio.getValue();
         //############# Fin Vehículo ###############

         //################## Automóvil ##################
         String combustible=Combustible.getSelectedItem().toString(), cambio=Cambio.getSelectedItem().toString();
         int plazas=(Integer)Plazas.getValue();
         //################## Fin Automóvil ##################
         Vehículo vehículo1 = null;
         
            if (tipoVehículo.equalsIgnoreCase("Motocicleta")) {
                vehículo1=new Motocicleta(tipoVehículo,(Integer)Cilindrada.getValue(), matrícula,marca,modelo,potencia,color,matriculación,kilometros,precio);

            }
            else if (tipoVehículo.equalsIgnoreCase("Todoterreno")) {
                vehículo1=new Todoterreno(Tracción.getSelectedItem().toString(),combustible,cambio, plazas, matrícula, marca, modelo, potencia, color, matriculación, kilometros, precio);
            }
            else if (tipoVehículo.equalsIgnoreCase("Turismo")) {
                vehículo1=new Turismo((Integer)Puertas.getValue(),combustible, cambio, plazas, matrícula, marca, modelo, potencia, color, matriculación, kilometros, precio);
            }
           Fichero fichero1=new Fichero();
           if (fichero1.altaVehículo(vehículo1)) {
                JOptionPane.showMessageDialog(this, "Persona dada de alta.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
           } else {
                JOptionPane.showMessageDialog(this, "Error al dar de alta.", "Mensaje", JOptionPane.ERROR_MESSAGE);
           }
         
    }
    catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Excepción al dar de alta.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_AltaActionPerformed

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:
    //Volvemos a mostrar la ventana principal
    principal.setVisible(true);
}//GEN-LAST:event_formWindowClosed

    private void MatriculaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculaciónActionPerformed

    private void TipoVehículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoVehículoActionPerformed
        // TODO add your handling code here:
        String tipoVehículo=TipoVehículo.getSelectedItem().toString();
        if (tipoVehículo.equalsIgnoreCase("Motocicleta")) {
            //no es automóvil
            muestraMotocicleta();
        }
        else if (tipoVehículo.equalsIgnoreCase("Todoterreno")) {
            muestraTodoterreno();
        }
        else if (tipoVehículo.equalsIgnoreCase("Turismo")) {
            muestraTurismo();
        }
        
    }//GEN-LAST:event_TipoVehículoActionPerformed
            
    void muestraMotocicleta() {
        oculta();
        Motocicleta.setVisible(true);
        
    }
    
    void oculta() {
        Todoterreno.setVisible(false);
        Automóvil.setVisible(false);
        Motocicleta.setVisible(false);
        Turismo.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alta;
    private javax.swing.JLayeredPane Automóvil;
    private javax.swing.JComboBox<String> Cambio;
    private javax.swing.JSpinner Cilindrada;
    private javax.swing.JTextField Color;
    private javax.swing.JComboBox<String> Combustible;
    private javax.swing.JLabel EtiquetaAutomóvilCambio;
    private javax.swing.JLabel EtiquetaAutomóvilCombustible;
    private javax.swing.JLabel EtiquetaAutomóvilPlazas;
    private javax.swing.JLabel EtiquetaMotocicletaCilindrada;
    private javax.swing.JLabel EtiquetaMotocicletaTipo;
    private javax.swing.JLabel EtiquetaTodoterrenoTracción;
    private javax.swing.JLabel EtiquetaTurismoPuertas;
    private javax.swing.JSpinner Kilómetros;
    private javax.swing.JTextField Marca;
    private javax.swing.JFormattedTextField Matriculación;
    private javax.swing.JTextField Matrícula;
    private javax.swing.JTextField Modelo;
    private javax.swing.JLayeredPane Motocicleta;
    private javax.swing.JSpinner Plazas;
    private javax.swing.JSpinner Potencia;
    private javax.swing.JSpinner Precio;
    private javax.swing.JSpinner Puertas;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JComboBox<String> TipoVehículo;
    private javax.swing.JLayeredPane Todoterreno;
    private javax.swing.JComboBox<String> Tracción;
    private javax.swing.JLayeredPane Turismo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void muestraTodoterreno() {
        oculta();
        Automóvil.setVisible(true);
        Todoterreno.setVisible(true);
    }

    private void muestraTurismo() {
        oculta();
        Automóvil.setVisible(true);
        Turismo.setVisible(true);
    }
}
;