/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico.administrador;

import grafico.administrador.AltaTurismo;
import grafico.administrador.AltaMotocicleta;
import grafico.administrador.AltaTodoterreno;
import java.awt.Image;
import javax.swing.ImageIcon;
import modelo.Empresa;


public class AltaVehiculo extends javax.swing.JFrame {
    
    private Empresa e;

    /**
     * Creates new form AltaVehiculo
     */
    
    public AltaVehiculo(Empresa e) {
        initComponents();
        this.e=e;
        Image icon = new ImageIcon(getClass().getResource("logo.png")).getImage();
        setIconImage(icon);
        this.setTitle("Alta de vehiculos");
        this.setLocation(700,300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        motocicleta = new javax.swing.JButton();
        tursimo = new javax.swing.JButton();
        todoterreno = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        motocicleta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        motocicleta.setText("Alta motocicleta");
        motocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motocicletaActionPerformed(evt);
            }
        });

        tursimo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tursimo.setText("Alta turismo");
        tursimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tursimoActionPerformed(evt);
            }
        });

        todoterreno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        todoterreno.setText("Alta todoterreno");
        todoterreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoterrenoActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(tursimo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(todoterreno)
                                    .addComponent(motocicleta))))
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(motocicleta)
                .addGap(29, 29, 29)
                .addComponent(tursimo)
                .addGap(36, 36, 36)
                .addComponent(todoterreno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void motocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motocicletaActionPerformed
        AltaMotocicleta rg = new AltaMotocicleta(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_motocicletaActionPerformed

    private void tursimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tursimoActionPerformed
        AltaTurismo rg = new AltaTurismo(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_tursimoActionPerformed

    private void todoterrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoterrenoActionPerformed
        AltaTodoterreno rg = new AltaTodoterreno(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_todoterrenoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JButton motocicleta;
    private javax.swing.JButton todoterreno;
    private javax.swing.JButton tursimo;
    // End of variables declaration//GEN-END:variables
}
