package grafico.administrador;

import censouni.Alumno;
import censouni.Persona;
import censouni.Profesor;
import censouni.UtilCenso;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class TipoVehículo extends javax.swing.JFrame {

    private JFrame principal;
    private String tipo = "";
    private Persona per = null;

    /** Creates new form Altas */
    public TipoVehículo(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        jComboBoxTipo.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonAltas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonAltas1 = new javax.swing.JButton();
        jButtonAltas2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Alta");

        jButtonAltas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAltas.setText("Motocicleta");
        jButtonAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltasActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/OcasionCar_Logo.png"))); // NOI18N

        jButtonAltas1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAltas1.setText("Todoterreno");
        jButtonAltas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltas1ActionPerformed(evt);
            }
        });

        jButtonAltas2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAltas2.setText("Turismo");
        jButtonAltas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltas2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAltas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAltas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAltas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButtonAltas)
                .addGap(28, 28, 28)
                .addComponent(jButtonAltas1)
                .addGap(30, 30, 30)
                .addComponent(jButtonAltas2)
                .addGap(37, 37, 37))
        );

        setSize(new java.awt.Dimension(415, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:
    //Volvemos a mostrar la ventana principal
    principal.setVisible(true);
}//GEN-LAST:event_formWindowClosed

//alta    
    private void jButtonAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltasActionPerformed
        // TODO add your handling code here:
        try {
            String dni = panelDatosCU.getJTextFieldDni();
            String nombre = panelDatosCU.getJTextFieldNom();
            LocalDate fn = panelDatosCU.getjSpinnerFecha();
            String dir = panelDatosCU.getJTextFieldDir();
            long tfno = panelDatosCU.getjFormattedTextFieldTfno();
            String var1 = panelDatosCU.getJTextFieldVar1();
            String var2 = panelDatosCU.getJTextFieldVar2();
            if (tipo.equals("Alumno")) {
                per = new Alumno(dni, nombre, fn, dir, tfno, var1, var2);
            } else {
                per = new Profesor(dni, nombre, fn, dir, tfno, var1, Double.parseDouble(var2));
            }
            //lo insertamos en el array
            if (UtilCenso.altaPersona(per)) {
                JOptionPane.showMessageDialog(this, "Persona dada de alta.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al dar de alta.", "Mensaje", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Excepción al dar de alta.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAltasActionPerformed

    private void jButtonAltas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAltas1ActionPerformed

    private void jButtonAltas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAltas2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltas;
    private javax.swing.JButton jButtonAltas1;
    private javax.swing.JButton jButtonAltas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
