package grafico.administrador;

import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Vehículo extends javax.swing.JFrame {

    private JFrame principal;
    private String tipo = "";

    /** Creates new form Altas */
    public Vehículo(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Motocicleta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Todoterreno = new javax.swing.JButton();
        Turismo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Alta");

        Motocicleta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Motocicleta.setText("Motocicleta");
        Motocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotocicletaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/OcasionCar_Logo.png"))); // NOI18N

        Todoterreno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Todoterreno.setText("Todoterreno");
        Todoterreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodoterrenoActionPerformed(evt);
            }
        });

        Turismo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Turismo.setText("Turismo");
        Turismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurismoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Todoterreno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Turismo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Motocicleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Motocicleta)
                .addGap(28, 28, 28)
                .addComponent(Todoterreno)
                .addGap(30, 30, 30)
                .addComponent(Turismo)
                .addGap(37, 37, 37))
        );

        setSize(new java.awt.Dimension(415, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:
    //Volvemos a mostrar la ventana principal
    principal.setVisible(true);
}//GEN-LAST:event_formWindowClosed

//alta    
    private void MotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotocicletaActionPerformed
        // TODO add your handling code here:
        Motocicleta altaMotocicleta1=new Motocicleta(this);
    }//GEN-LAST:event_MotocicletaActionPerformed

    private void TodoterrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodoterrenoActionPerformed
        // TODO add your handling code here:
        Todoterreno todoterreno1=new Todoterreno(this);
    }//GEN-LAST:event_TodoterrenoActionPerformed

    private void TurismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurismoActionPerformed
        // TODO add your handling code here:
        Turismo turismo1=new Turismo(this);
    }//GEN-LAST:event_TurismoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Motocicleta;
    private javax.swing.JButton Todoterreno;
    private javax.swing.JButton Turismo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
