/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico.administrador;

import java.awt.Image;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Venta;


public class VentanaVenta extends javax.swing.JFrame {


    private ArrayList<Venta> mostrarVentas;
    private int contador = 0;
    private Empresa e;

    /**
     * Creates new form Ventas
     */
    
    public VentanaVenta(Empresa e) {
        initComponents();
        this.e = e;
        Image icon = new ImageIcon(getClass().getResource("logo.png")).getImage();
        setIconImage(icon);
        this.setTitle("Consulta de ventas");
        this.setLocation(700, 300);
        siguiente.setEnabled(false);
    }

    
    public void mostrarSiguiente() {
        if (contador < mostrarVentas.size()) {
            String infoVenta = "Vehiculo vendido: " + e.getVentas().get(contador).getV().getMarca()
                    + e.getVentas().get(contador).getV().getModelo()
                    + " con matricula: " + e.getVentas().get(contador).getV().getMatricula()
                    + "\n" + "Cliente-- " + "Nombre: " + e.getVentas().get(contador).getC().getNombre()
                    + " con DNI: " + e.getVentas().get(contador).getC().getDni()
                    + " y correo: " + e.getVentas().get(contador).getC().getCorreo()
                    + "\n" + "Fecha: " + e.getVentas().get(contador).getFecha().getDay() + e.getVentas().get(contador).getFecha().getMonth()
                    + e.getVentas().get(contador).getFecha().getYear()
                    + "\n" + "Precio: " + e.getVentas().get(contador).getPrecio();
            txt_area.setText(infoVenta);
            contador++;
        } else {
            JOptionPane.showMessageDialog(this, "No hay mas ventas efectuadas");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        siguiente = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        mostrar.setText("Mostrar todas las ventas");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(mostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente)
                    .addComponent(mostrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        mostrarVentas = e.getVentas();
        contador = 0;
        if (e.getVentas().size() == 0) {
            JOptionPane.showMessageDialog(this, "No hay ventas");
        } else {
            siguiente.setEnabled(true);

            mostrarSiguiente();
        }

    }//GEN-LAST:event_mostrarActionPerformed


    
    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        mostrarSiguiente();
    }//GEN-LAST:event_siguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrar;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextArea txt_area;
    // End of variables declaration//GEN-END:variables
}
