/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import interfaz.AltaTurismo;
import interfaz.AltaMotocicleta;
import interfaz.AltaTodoterreno;
import java.awt.Image;
import javax.swing.ImageIcon;
import clases.Empresa;

/**
 *interfaz para visualizar y elegir el tipo de vehiculo que queremos dar de alta
 * @author david
 */
public class AltaVehiculo extends javax.swing.JFrame {
    //campos
    private Empresa e;

    /**
     * Creates new form AltaVehiculo
     */
    /**
     * constructor
     *
     * @param e es la empresa sobre la que estamos trabajando
     */
    public AltaVehiculo(Empresa e) {
        initComponents();
        this.e=e;
        Image icon = new ImageIcon(getClass().getResource("logo.png")).getImage();
        setIconImage(icon);
        this.setTitle("Alta de vehiculos");
        this.setLocation(700,300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        motocicleta = new javax.swing.JButton();
        tursimo = new javax.swing.JButton();
        todoterreno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        motocicleta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        motocicleta.setText("Dar de alta una motocicleta");
        motocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motocicletaActionPerformed(evt);
            }
        });

        tursimo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tursimo.setText("Dar de alta un turismo");
        tursimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tursimoActionPerformed(evt);
            }
        });

        todoterreno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        todoterreno.setText("Dar de alta un todoterreno");
        todoterreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoterrenoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(tursimo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(todoterreno)
                            .addComponent(motocicleta))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(motocicleta)
                .addGap(29, 29, 29)
                .addComponent(tursimo)
                .addGap(36, 36, 36)
                .addComponent(todoterreno)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * metodos para llevar al administrador a diferentes ventanas segun elija el tipo de vehiculo que
 * quiere dar de alta
 * @param evt los metodos seran activados cuando sus respectivos botones sean presionados
 */
    private void motocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motocicletaActionPerformed
        AltaMotocicleta rg = new AltaMotocicleta(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_motocicletaActionPerformed

    private void tursimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tursimoActionPerformed
        AltaTurismo rg = new AltaTurismo(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_tursimoActionPerformed

    private void todoterrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoterrenoActionPerformed
        AltaTodoterreno rg = new AltaTodoterreno(this.e);
        rg.setVisible(true);
    }//GEN-LAST:event_todoterrenoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton motocicleta;
    private javax.swing.JButton todoterreno;
    private javax.swing.JButton tursimo;
    // End of variables declaration//GEN-END:variables
}
