/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.Empresa;

/**
 * clase para dar de baja un cliente buscandolo en nuestro hashmap y
 * eliminandolo
 *
 * @author david
 */
public class BajaCliente extends javax.swing.JFrame {

    //camposq

    private Empresa e;

    /**
     * Creates new form BajaCliente
     */
    /**
     * constructor
     *
     * @param e es la empresa sobre la que estamos trabajando
     */
    public BajaCliente(Empresa e) {
        initComponents();
        this.e = e;
        Image icon = new ImageIcon(getClass().getResource("logo.png")).getImage();
        setIconImage(icon);
        this.setTitle("Baja de clientes");
        this.setLocation(700, 300);

    }//fin constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        bajaCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Correo");

        bajaCliente.setText("Dar de Baja");
        bajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(bajaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(bajaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * metodo para buscar un cliente en nuestro hashmap y eliminarlo
     *
     * @param evt el motodo se activara cuando el boton sea pulsado
     */
    private void bajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaClienteActionPerformed

        String correo = txt_correo.getText();

        if (e.getClientes().containsKey(correo)) {
            e.getClientes().remove(correo);
            e.guardarDatosClientes();
            JOptionPane.showMessageDialog(this, "Cliente dado de baja correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado");

        }


    }//GEN-LAST:event_bajaClienteActionPerformed
//fin del metodo

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajaCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_correo;
    // End of variables declaration//GEN-END:variables
}
