/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Image;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.Cliente;
import clases.Empresa;
import clases.Vehiculo;
import clases.Venta;

/**
 * interfaz para que el usuario busque un vehiculo por marca y modelo y pueda
 * comprarlo generandose y guardandose automaticamente una factura
 *
 * @author david
 */
public class BuscarVehiculo extends javax.swing.JFrame {
//campos

    private ArrayList<Vehiculo> mostrarVehiculos;
    private Empresa e;
    private int contador = 0;
    private Cliente c;

    /**
     * Creates new form BuscarVehiculo
     */
    /**
     * constructor
     *
     * @param e empresa con la que trabajamos
     * @param c cliente el cual ha accedido a la pagina
     */
    public BuscarVehiculo(Empresa e, Cliente c) {
        initComponents();
        this.e = e;
        this.c = c;
        this.setTitle("Consulta de vehiculos");
        this.setLocation(700, 300);
        siguiente.setEnabled(false);
    }//fin constructor

    /**
     * metodo para calcular el precio final del vehiculo aplicando el desceunto
     * correpondiente dependiendo de la relacion del cliente con la empresa
     *
     * @return precio final del vehiculo
     */
    public double calcularPrecio() {
        int precio = mostrarVehiculos.get(contador - 1).getPrecio();
        if (c.getRelacion().equals("Familiar")) {
            precio = (int) (precio * 0.90);
        } else if (c.getRelacion().equals("Empleado")) {
            precio = (int) (precio * 0.75);
        }

        return precio;
    }//fin del metodo

    /**
     * metodo para mostrar el vehiculo correspondiente
     */
    public void mostrarSiguiente() {
        if (contador < mostrarVehiculos.size()) {
            String infoCoche = "El color es: " + mostrarVehiculos.get(contador).getColor()
                    + "\n" + "La marca es: " + mostrarVehiculos.get(contador).getMarca()
                    + "\n" + "La matricula es: " + mostrarVehiculos.get(contador).getMatricula()
                    + "\n" + "El modelo es: " + mostrarVehiculos.get(contador).getModelo()
                    + "\n" + "El fecha de matriculacion es: " + mostrarVehiculos.get(contador).getFechamat()
                    + "\n" + "Tiene " + mostrarVehiculos.get(contador).getKilometros() + " kilometros"
                    + "\n" + "Su potencia es: " + mostrarVehiculos.get(contador).getPotencia()
                    + "\n" + "El precio es: " + mostrarVehiculos.get(contador).getPrecio();
            txt_area.setText(infoCoche);
            lbl_foto.setIcon(mostrarVehiculos.get(contador).getFoto());
            contador++;
        } else {
            JOptionPane.showMessageDialog(this, "No hay mas vehiculos disponibles");

        }

    }//fin del metodo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        lbl_foto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        comprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        siguiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Busqueda de vehiculos :");

        jLabel2.setText("Introduzca la marca");

        jLabel3.setText("Introduzca el modelo");

        comprar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(comprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(375, 375, 375)
                                .addComponent(buscar)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buscar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente)
                    .addComponent(comprar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * metodo para crear un ArrayList auxiliar con solo los vehiculos que
     * cumplan los criterios establecidos por el usuario
     *
     * @param evt metodo sera ejecutado cuando el boton sea pulsado
     */
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        mostrarVehiculos = new ArrayList<>();
        contador = 0;
        for (int i = 0; i < e.getVehiculos().size(); i++) {
            if (e.getVehiculos().get(i).getMarca().equals(txt_marca.getText()) && e.getVehiculos().get(i).getModelo().equals(txt_marca.getText())) {
                mostrarVehiculos.add(e.getVehiculos().get(i));
            }
        }
        if (mostrarVehiculos.size() == 0) {
            JOptionPane.showMessageDialog(this, "No hay vehiculos con estas caracteristicas");
        } else {
            siguiente.setEnabled(true);
            mostrarSiguiente();
        }
    }//GEN-LAST:event_buscarActionPerformed
//fin del metodo

    /**
     * metodo para mostrar el vehiculo siguiente de nuestro ArrayList auxiliar
     *
     * @param evt metodo sera ejecutado cuando el boton sea pulsado
     */
    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        mostrarSiguiente();
    }//GEN-LAST:event_siguienteActionPerformed
//fin del metodo
    /**
     * metodo para comprar un vehiculo y asi retirarlo del arraylist de
     * vehiculos este metodo nos genera una factura con los datos de la compra y
     * la almacena en el arraylist de ventas
     *
     * @param evt
     */
    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        try {
            int precio = mostrarVehiculos.get(contador - 1).getPrecio();
            double preciofinal = calcularPrecio();
            int año = Integer.valueOf(JOptionPane.showInputDialog("Introducir año de la compra: "));
            int mes = Integer.valueOf(JOptionPane.showInputDialog("Introducir mes de la compra: "));
            int dia = Integer.valueOf(JOptionPane.showInputDialog("Introducir dia de la compra: "));
            Date fecha = new Date(año, mes, dia);
            Venta v = new Venta(mostrarVehiculos.get(contador - 1), c, fecha, preciofinal);
            e.getVentas().add(v);
            e.guardarDatosVentas();
            for (int i = 0; i < e.getVehiculos().size(); i++) {
                if (mostrarVehiculos.get(contador - 1).getMatricula().equals(e.getVehiculos().get(i).getMatricula())) {
                    e.getVehiculos().remove(i);
                }
            }
            e.guardarDatosVehiculos();
            v.generarFactura();
            JOptionPane.showMessageDialog(this, "Vehiculo comprado con exito");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Excepción: no ha seleccionado ningún vehículo", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_comprarActionPerformed
//fin del metodo

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton comprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    // End of variables declaration//GEN-END:variables
}
