/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.Empresa;
import clases.Vehiculo;

/**
 *interfaz para mostrar los vehiculos que cumplan las caracteristicas introducidas
 * @author david
 */
public class Consulta extends javax.swing.JFrame {
//campos
    private ArrayList<Vehiculo> mostrarVehiculos;
    private Empresa e;
    private int contador = 0;

    /**
     * Creates new form Consulta
     */
    /**
     * constructor
     * @param e empresa con la que trabajamos
     */
    public Consulta(Empresa e) {
        initComponents();
        this.e = e;
        Image icon = new ImageIcon(getClass().getResource("logo.png")).getImage();
        setIconImage(icon);
        this.setTitle("Consulta de vehiculos");
        this.setLocation(700, 300);
        siguiente.setEnabled(false);

    }//fin del constructor
/**
 * metodo para mostrar el vehiculo correspondiente
 */
    public void mostrarSiguiente() {
        if (contador < mostrarVehiculos.size()) {
            String infoCoche = "El color es: " + mostrarVehiculos.get(contador).getColor()
                    + "\n" + "La marca es: " + mostrarVehiculos.get(contador).getMarca()
                    + "\n" + "La matricula es: " + mostrarVehiculos.get(contador).getMatricula()
                    + "\n" + "El modelo es: " + mostrarVehiculos.get(contador).getModelo()
                    + "\n" + "El fecha de matriculacion es: " + mostrarVehiculos.get(contador).getFechamat()
                    + "\n" + "Tiene " + mostrarVehiculos.get(contador).getKilometros() + " kilometros"
                    + "\n" + "Su potencia es: " + mostrarVehiculos.get(contador).getPotencia()
                    + "\n" + "El precio es: " + mostrarVehiculos.get(contador).getPrecio();
            txt_area.setText(infoCoche);
            contador++;
        } else {
            JOptionPane.showMessageDialog(this, "No hay mas vehiculos disponibles");

        }

    }//fin del metodo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        todos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Busqueda de vehiculos :");

        jLabel2.setText("Introduzca la marca");

        jLabel3.setText("Introduzca el modelo");

        buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        siguiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        todos.setText("Mostrar todos los vehiculos");
        todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 607, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel1)
                            .addGap(133, 133, 133)
                            .addComponent(todos))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(jLabel2)
                            .addGap(35, 35, 35)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(72, 72, 72)
                            .addComponent(jLabel3)
                            .addGap(38, 38, 38)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(375, 375, 375)
                            .addComponent(buscar))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(todos))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(siguiente)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * metodo para crear un ArrayList auxiliar con solo los vehiculos que
     * cumplan los criterios establecidos por el usuario
     *
     * @param evt metodo sera ejecutado cuando el boton sea pulsado
     */
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        mostrarVehiculos = new ArrayList<>();
        contador = 0;
        for (int i = 0; i < e.getVehiculos().size(); i++) {
            if (e.getVehiculos().get(i).getMarca().equals(txt_marca.getText()) && e.getVehiculos().get(i).getModelo().equals(txt_marca.getText())) {
                mostrarVehiculos.add(e.getVehiculos().get(i));
            }
        }
        if (mostrarVehiculos.size() == 0) {
            JOptionPane.showMessageDialog(this, "No hay vehiculos con estas caracteristicas");
        } else {
            siguiente.setEnabled(true);

            mostrarSiguiente();
        }


    }//GEN-LAST:event_buscarActionPerformed
//fin del metodo
    /**
     * metodo para mostrar el vehiculo siguiente de nuestro ArrayList auxiliar
     *
     * @param evt metodo sera ejecutado cuando el boton sea pulsado
     */
    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        mostrarSiguiente();
    }//GEN-LAST:event_siguienteActionPerformed
//fin del metodo
    /**
     * metodo para mostrar todos los vehiculos dados de alta
     * @param evt 
     */
    private void todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosActionPerformed
        mostrarVehiculos = e.getVehiculos();
        contador = 0;
        if (mostrarVehiculos.size() == 0) {
            JOptionPane.showMessageDialog(this, "No hay vehiculos");
        } else {
            siguiente.setEnabled(true);

            mostrarSiguiente();
        }
    }//GEN-LAST:event_todosActionPerformed
//fin del metodo

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton siguiente;
    private javax.swing.JButton todos;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    // End of variables declaration//GEN-END:variables
}
