/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Empresa;
import modelo.Vehiculo;
import modelo.Venta;


public class BuscaVehiculo extends javax.swing.JFrame {


    private ArrayList<Vehiculo> mostrarVehiculos;
    private Empresa e;
    private int contador = 0;
    private Cliente cliente;

    
    public BuscaVehiculo(Empresa e, Cliente c) {
        initComponents();
        this.e = e;
        this.cliente = c;
        this.setTitle("Consulta de vehiculos");
        this.setLocation(700, 300);
        siguiente.setEnabled(false);
    }

    
    public double calcularPrecio() {
        int precio = mostrarVehiculos.get(contador - 1).getPrecio();
        if (cliente.getRelacion().equals("Familiar")) {
            precio = (int) (precio * 0.90);
        } else if (cliente.getRelacion().equals("Empleado")) {
            precio = (int) (precio * 0.75);
        }

        return precio;
    }

   
    public void mostrarSiguiente() {
        if (contador < mostrarVehiculos.size()) {
            String infoCoche = "El color es: " + mostrarVehiculos.get(contador).getColor()
                    + "\n" + "La marca es: " + mostrarVehiculos.get(contador).getMarca()
                    + "\n" + "La matricula es: " + mostrarVehiculos.get(contador).getMatricula()
                    + "\n" + "El modelo es: " + mostrarVehiculos.get(contador).getModelo()
                    + "\n" + "El fecha de matriculacion es: " + mostrarVehiculos.get(contador).getFechamat()
                    + "\n" + "Tiene " + mostrarVehiculos.get(contador).getKilometros() + " kilometros"
                    + "\n" + "Su potencia es: " + mostrarVehiculos.get(contador).getPotencia()
                    + "\n" + "El precio es: " + mostrarVehiculos.get(contador).getPrecio();
            txt_area.setText(infoCoche);
            lbl_foto.setIcon(mostrarVehiculos.get(contador).getFoto());
            contador++;
        } else {
            JOptionPane.showMessageDialog(this, "No hay mas vehiculos disponibles");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        lbl_foto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        comprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscar.setText("Busca");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        siguiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        comprar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comprar.setText("Compra");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(buscar)
                .addGap(117, 117, 117)
                .addComponent(comprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente)
                    .addComponent(comprar)
                    .addComponent(buscar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        mostrarVehiculos = new ArrayList<>();
        contador = 0;
        for (int i = 0; i < e.getVehiculos().size(); i++) {
            if (e.getVehiculos().get(i).getMarca().equals(txt_marca.getText()) && e.getVehiculos().get(i).getModelo().equals(txt_marca.getText())) {
                mostrarVehiculos.add(e.getVehiculos().get(i));
            }
        }
        if (mostrarVehiculos.size() == 0) {
            JOptionPane.showMessageDialog(this, "No hay vehiculos con estas caracteristicas");
        } else {
            siguiente.setEnabled(true);
            mostrarSiguiente();
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        mostrarSiguiente();
    }//GEN-LAST:event_siguienteActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        try {
            int precio = mostrarVehiculos.get(contador - 1).getPrecio();
            double preciofinal = calcularPrecio();
            int año = Integer.valueOf(JOptionPane.showInputDialog("Introducir año de la compra: "));
            int mes = Integer.valueOf(JOptionPane.showInputDialog("Introducir mes de la compra: "));
            int dia = Integer.valueOf(JOptionPane.showInputDialog("Introducir dia de la compra: "));
            Date fecha = new Date(año, mes, dia);
            Venta v = new Venta(mostrarVehiculos.get(contador - 1), cliente, fecha, preciofinal);
            e.getVentas().add(v);
            e.guardarDatosVentas();
            for (int i = 0; i < e.getVehiculos().size(); i++) {
                if (mostrarVehiculos.get(contador - 1).getMatricula().equals(e.getVehiculos().get(i).getMatricula())) {
                    e.getVehiculos().remove(i);
                }
            }
            e.guardarDatosVehiculos();
            v.generarFactura();
            JOptionPane.showMessageDialog(this, "Vehiculo comprado con exito");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Excepción: no ha seleccionado ningún vehículo", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_comprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton comprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    // End of variables declaration//GEN-END:variables
}
