package grafico;

import grafico.administrador.Administrador;
import java.util.Arrays;
import modelo.Main;


public class Inicio extends javax.swing.JFrame {
    
    /** Creates new form Censo */
    public Inicio() {
        //UtilCenso.cargarDatos();
        initComponents();        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciaSesion = new javax.swing.JButton();
        Registra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        clave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        iniciaSesion.setText("Inicia sesión");
        iniciaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciaSesionActionPerformed(evt);
            }
        });
        getContentPane().add(iniciaSesion);
        iniciaSesion.setBounds(120, 220, 160, 29);

        Registra.setText("Registrame");
        Registra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraActionPerformed(evt);
            }
        });
        getContentPane().add(Registra);
        Registra.setBounds(120, 260, 160, 29);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/OcasionCar_Logo.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 10, 160, 110);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clave");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 180, 70, 16);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 150, 70, 16);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre);
        nombre.setBounds(190, 150, 120, 26);

        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });
        getContentPane().add(clave);
        clave.setBounds(190, 180, 120, 26);

        setSize(new java.awt.Dimension(396, 342));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
        //UtilCenso.guardarDatos();
    }//GEN-LAST:event_formWindowClosing

    //BUSQUEDAS
    private void RegistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraActionPerformed
// TODO add your handling code here:
        //Cliente b = new Cliente(this);
        //Registro registro1 = new Registro(this);
        Parentesco parentesco1=new Parentesco(this);
    }//GEN-LAST:event_RegistraActionPerformed
    
    //CONSULTAS
    private void iniciaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaSesionActionPerformed
        // TODO add your handling code here:
        //VentanaConsultas c = new VentanaConsultas(this);
        //############# Desactivado por pruebas ##############
        if (nombre.getText().equalsIgnoreCase("admin@ocasioncar.com") && String.valueOf(clave.getPassword()).equals("admin")) { //la contraseña es sensible a minusculas y mayusculas
            Administrador administrador1 = new Administrador(this);
        }
        /*else if (Main.getPersonas().contains(nombre)) {
            
        }*/
    }//GEN-LAST:event_iniciaSesionActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registra;
    private javax.swing.JPasswordField clave;
    private javax.swing.JButton iniciaSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
   
}
