package grafico;

import censouni.Alumno;
import censouni.Persona;
import censouni.Profesor;
import censouni.UtilCenso;
import java.awt.HeadlessException;
import java.io.IOException;
import java.time.Instant;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Parentesco extends javax.swing.JFrame {

    private JFrame principal;

    /** Creates new form Busquedas */
    public Parentesco(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        panelDatosCU.setEtiVar1("");
        panelDatosCU.setEtiVar2("");
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonImprimir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonImprimir1 = new javax.swing.JButton();
        jButtonImprimir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Búsquedas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cliente");

        jButtonImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonImprimir.setText("Ninguna relación");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/OcasionCar_Logo.png"))); // NOI18N

        jButtonImprimir1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonImprimir1.setText("Familiar");
        jButtonImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimir1ActionPerformed(evt);
            }
        });

        jButtonImprimir2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonImprimir2.setText("Amigo");
        jButtonImprimir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonImprimir2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonImprimir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addGap(44, 44, 44)
                .addComponent(jButtonImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonImprimir1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonImprimir2)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(415, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:
    principal.setVisible(true);
}//GEN-LAST:event_formWindowClosed

private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
    // TODO add your handling code here:
    String dni = panelDatosCU.getJTextFieldDni();
    if (dni.equals("")) {
        JOptionPane.showMessageDialog(this, "Rellene el DNI de la persona.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    try {
        //obtenemos la persona
        Persona per = UtilCenso.consultaPersonaPorDni(dni);

        if (per != null) {
            presenta(per);           
            UtilCenso.generaFicha(per);
            JOptionPane.showMessageDialog(this, "Ficha de la persona generada: " + per.getDni() + ".txt", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            panelDatosCU.borrar();
            JOptionPane.showMessageDialog(this, " Error: - Persona no encontrada - ", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    } catch (IOException | HeadlessException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        System.out.println("Error: " + e.toString());
    }
}//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimir1ActionPerformed

    private void jButtonImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimir2ActionPerformed

    /** Presenta los datos de una persona en el panel de datos */
    private void presenta(Persona per) {
        String tipo = per.getClass().getSimpleName();
        panelDatosCU.setJTextFieldDni(per.getDni());
        panelDatosCU.setJTextFieldNom(per.getNombre());
        Instant instant = per.getFechaNac().atStartOfDay().atZone(ZoneId.systemDefault()).toInstant();
        Date fecha = Date.from(instant);
        panelDatosCU.setjSpinnerFecha(fecha);
        panelDatosCU.setJTextFieldDir(per.getDireccion());
        panelDatosCU.setjFormattedTextFieldTfno(per.getTfno());

        if (tipo.equals("Alumno")) {
            Alumno alu = (Alumno) per;
            panelDatosCU.setEtiVar1("TITULACIÓN");
            panelDatosCU.setEtiVar2("ASIGNATURAS");
            panelDatosCU.setJTextFieldVar1(alu.getTitulacion());
            panelDatosCU.setJTextFieldVar2(alu.getAsignaturas());
        } else {
            Profesor pro = (Profesor) per;
            panelDatosCU.setEtiVar1("DEPT.");
            panelDatosCU.setEtiVar2("SUELDO");
            panelDatosCU.setJTextFieldVar1(pro.getDepartamento());
            panelDatosCU.setJTextFieldVar2("" + pro.getSueldo());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonImprimir1;
    private javax.swing.JButton jButtonImprimir2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
